version: "3.9"
services:
  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    volumes:
      - ~/.ceramic/:/root/.ceramic/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:7007/api/v0/node/healthcheck || exit 1"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dapp-backend:
    image: dataverseos/dapp-backend:latest
    environment:
      - DID_PRIVATE_KEY={YOUR_PRIVATE_KEY}
      - CERAMIC_URL=http://ceramic:7007
    ports:
      - "8080:8080"
    depends_on:
      - ceramic
