version: "3.9"
services:
  ceramic:
    image: ceramicnetwork/composedb:2.35.0
    volumes:
      - ~/.ceramic/:/root/.ceramic/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:7007/api/v0/node/healthcheck || exit 1"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dapp-backend:
    image: ghcr.io/dataverse-os/dapp-backend:latest
    environment:
      - CERAMIC_URL=http://ceramic:7007
    env_file:
      - .private-key.env
    ports:
      - "8080:8080"
    depends_on:
      - ceramic
