name: Test and coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: generate js-scripts
        working-directory: js-scripts
        run: |
          npm install
          npm run build

      - name: setup ceramic private key
        id: ceramic-secret
        run: |
          npm install -g @composedb/cli@^0.4.0
          export CERAMIC_ADMIN_KEY=$(openssl rand -hex 32)
          echo "CERAMIC_ADMIN_KEY=$CERAMIC_ADMIN_KEY" >> "$GITHUB_OUTPUT"
          echo "CERAMIC_ADMIN_DID=$(composedb did:from-private-key $CERAMIC_ADMIN_KEY})" >> "$GITHUB_OUTPUT"

      - name: setup ceramic instance
        run: |
          npm install -g @ceramicnetwork/cli
          mkdir -p ~/.ceramic
          envsubst < ./daemon.config.json > ~/.ceramic/daemon.config.json
          ceramic daemon &
        env:
          CERAMIC_ADMIN_KEY: ${{ steps.ceramic-secret.outputs.CERAMIC_ADMIN_KEY }}
          CERAMIC_NETWORK: inmemory
      
      - name: check ceramic instance status
        run: curl http://localhost:7007/api/v0/node/healthcheck

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          CERAMIC_URL: http://localhost:7007
          CERAMIC_ADMIN_KEY: ${{ steps.ceramic-secret.outputs.CERAMIC_ADMIN_KEY }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3